# Run Continuous Integration on every push
# This tests Python 3.5.1
name: python_compatibility_3.5.1
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python 3.5.1 eggs
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.eggs
        key: python-compatibility-3.5.1-eggs

    - name: Run tests on 3.5.1 latest
      run: docker run -v "${GITHUB_WORKSPACE}:/home/yatiml" python:3.5.1 /bin/bash -c 'cd /home/yatiml && pip install -U pip setuptools wheel && python setup.py test'
