name: Tortellini dependency license check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tortellini-tools/action@main
